[hacktogether] Add support for micro-segmentation creation within Athenz UI.
AthenZ/athenz pull request #1406
Opened 2021-03-29 03:51 UTC by jothi-prasad

2021-04-03 23:16 UTC, abvaidya requested changes
Please change copyright to Athenz Authors.

2021-04-05 20:09 UTC, jothi-prasad commented
> Please change copyright to Athenz Authors.

is there a sample to follow.. i see the same pattern followed in other files too for ex: https://github.com/AthenZ/athenz/blob/master/ui/src/components/policy/AddPolicy.js

2021-04-06 21:03 UTC, pratikgote requested changes

2021-04-06 21:03 UTC, pratikgote commented on ui/src/components/microsegmentation/AddSegmentation.js
> +    ServiceChange(chosen, key) {
changeService?

2021-04-06 21:03 UTC, pratikgote commented on ui/src/components/microsegmentation/AddStaticInstances.js
> +const Resourcetypes = [
can we move this to consts file?

2021-04-06 21:03 UTC, pratikgote commented on ui/src/components/microsegmentation/AddStaticInstances.js
> +        let names = (resourceVal || '')
can we move this code to NameUtils.js and replace it everywhere this code is being used?

2021-04-06 21:19 UTC, abvaidya commented
Chandu will address review comments in his PR.

2021-04-06 21:19 UTC, merged