Extending Microsegmentation daemon api
AthenZ/athenz pull request #1555
Opened 2021-07-18 07:29 UTC by psasidhar

2021-07-20 00:01 UTC, abvaidya requested changes

2021-07-20 00:01 UTC, abvaidya commented on core/msd/src/main/rdl/Workload.tdl
> +type WorkloadRecord Workload {
why do we need this defined in RDL?

2021-07-26 15:33 UTC, havetisyan requested changes

2021-07-26 15:33 UTC, havetisyan commented on libs/java/server_common/src/main/java/com/yahoo/athenz/common/server/workload/WorkloadData.java
> +package com.yahoo.athenz.common.server.workload;
need copyright

2021-07-26 15:34 UTC, havetisyan commented
@psasidhar two files still missing copyright details

2021-07-26 22:24 UTC, psasidhar commented on core/msd/src/main/rdl/Workload.tdl
> +type WorkloadRecord Workload {
removed it

2021-07-26 23:14 UTC, havetisyan approved these changes

2021-07-26 23:14 UTC, merged