Endpoint to get dependent services and resource groups
AthenZ/athenz pull request #1818
Opened 2022-03-20 12:22 UTC by OferLevi85

Signed-off-by: Ofer Levi <ofer.levi@verizonmedia.com>

2022-03-22 16:27 UTC, havetisyan requested changes

2022-03-22 16:27 UTC, havetisyan commented on servers/zms/src/main/java/com/yahoo/athenz/zms/ZMSImpl.java
> +    private List<String> getResourceGroupsForProviderServiceTenantDomain(String service, String tenantDomain) {
let's mark service and tenantDomain arguments as final

2022-03-23 07:49 UTC, OferLevi85 commented on servers/zms/src/main/java/com/yahoo/athenz/zms/ZMSImpl.java
> +        String finalDomainName = domainName;
Lambda required a "final" parameter. I can't set the original domainName final as we might change it by lowercasing.

2022-03-23 16:54 UTC, havetisyan commented on servers/zms/src/main/java/com/yahoo/athenz/zms/ZMSImpl.java
> +        String finalDomainName = domainName;
but finalDomainName isn't marked final?

2022-03-23 17:41 UTC, OferLevi85 commented on servers/zms/src/main/java/com/yahoo/athenz/zms/ZMSImpl.java
> +        String finalDomainName = domainName;
Yeah, I apparently making a new variable that never changes is enough as it is considered "effectively final". 
I agree that it isn't very clear so I'll add the final keyword.

2022-03-23 19:31 UTC, havetisyan approved these changes

2022-03-23 19:31 UTC, merged