Heap inspection
AthenZ/athenz pull request #1825
Opened 2022-03-25 15:30 UTC by abvaidya

also addresses #1824

2022-03-25 16:06 UTC, abvaidya commented on libs/java/server_common/src/main/java/com/yahoo/athenz/auth/impl/aws/AwsPrivateKeyStore.java
> +        return pkey == null ? null : new ServerPrivateKey(pkey, new String(getDecryptedData(bucketName, keyIdName)));
using new String to create string from byte[]

2022-03-25 16:08 UTC, abvaidya commented on libs/java/server_common/src/main/java/com/yahoo/athenz/auth/impl/aws/AwsPrivateKeyStore.java
> +    private byte[] getDecryptedData(final String bucketName, final String keyName) {
changing return type from string to byte[]

2022-03-25 16:08 UTC, abvaidya commented on libs/java/server_common/src/main/java/com/yahoo/athenz/auth/impl/aws/AwsPrivateKeyStore.java
> +            secret[i] = (char) secretBytes[i];
attention

2022-03-25 20:19 UTC, havetisyan requested changes

2022-03-27 17:37 UTC, havetisyan approved these changes

2022-03-27 17:38 UTC, merged