Rename variables and include project id in view
AthenZ/athenz pull request #2110
Opened 2023-03-24 21:47 UTC by jimmytsang

2023-03-24 22:12 UTC, chandrasekhar1996 requested changes

2023-03-25 00:09 UTC, jimmytsang commented on ui/src/pages/gcp/login.js
> +    if (splitStrings.length < 1) return '';
updated conditional to ` if (splitStrings.length < 1 || splitStrings[0] !== 'projects') return '';`

2023-03-25 00:10 UTC, jimmytsang commented on ui/src/pages/gcp/login.js
>      populateProjects() {
sure, renamed to `getAssertionlist`

2023-03-25 02:47 UTC, chandrasekhar1996 approved these changes

2023-03-25 15:25 UTC, merged