display warning for expired and disabled members in Roles and Groups
AthenZ/athenz pull request #2668
Opened 2024-08-01 15:16 UTC by ArtjomsPorss

# Description
Changes affect Roles and Groups Members screen. Shows a warning icon if a Member is disabled or expired. Tooltip of warning icon shows disability reason.

# Contribution Checklist:
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have read the [contribution guidelines](https://github.com/AthenZ/athenz/blob/master/CONTRIBUTING.md).**
- [ ] **Create an issue and link to the pull request.**

## Attach Screenshots (Optional) 
- Shows warning icon with a tooltip and displays date in red for expired members:
![Screenshot 2024-07-31 at 16 53 24](https://github.com/user-attachments/assets/1266aa57-ec09-4dab-bd46-d5c6024f6f25)
- Shows warning icon for disabled members. Tooltip describes disability reason.
![Screenshot 2024-07-31 at 17 04 09](https://github.com/user-attachments/assets/2bb5dfe8-79c8-4bb4-ac0e-babf657f5ced)

2024-08-01 20:01 UTC, chandrasekhar1996 requested changes

2024-08-02 15:48 UTC, ArtjomsPorss commented on ui/src/components/member/MemberRow.js
> +    ${props => props.expired && `font-style: ${props.fontStyle};`}
@chandrasekhar1996 is this what you meant it to look like?

2024-08-02 16:10 UTC, chandrasekhar1996 approved these changes

2024-08-02 17:41 UTC, chandrasekhar1996 approved these changes

2024-08-02 17:42 UTC, merged