add group review icon, it becomes red when group review required
AthenZ/athenz pull request #2705
Opened 2024-08-27 14:37 UTC by ArtjomsPorss

# Description
1. Added icon in Groups view which opens Group Review page.
2. The icon becomes red and text changes to "Review Required" when last review was more than 80% of min Review/Expiry days ago (set in settings).
3. Moved logic that determines whether a review is required from RoleRow to RoleAndGroupReview, as it is now also used by GroupRow

# Contribution Checklist:
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have read the [contribution guidelines](https://github.com/AthenZ/athenz/blob/master/CONTRIBUTING.md).**
- [ ] **Create an issue and link to the pull request.**

## Attach Screenshots (Optional) 
![image](https://github.com/user-attachments/assets/2351ac6c-3c5f-4256-9d39-ca1988211c17)

2024-08-30 21:29 UTC, chandrasekhar1996 commented on ui/src/components/role-and-group-review/RoleAndGroupReview.js
> +import { PERCENTAGE_OF_DAYS_TILL_NEXT_REVIEW } from '../constants/constants';
can we move this to utils directory

2024-09-02 14:39 UTC, ArtjomsPorss commented on ui/src/components/role-and-group-review/RoleAndGroupReview.js
> +import { PERCENTAGE_OF_DAYS_TILL_NEXT_REVIEW } from '../constants/constants';
done

2024-09-02 16:49 UTC, chandrasekhar1996 approved these changes

2024-09-02 17:12 UTC, abvaidya requested changes

2024-09-02 17:12 UTC, abvaidya commented on ui/src/__tests__/components/utils/ReviewUtils.test.js
> +import moment from 'moment-timezone';
please add license text on all new files

2024-09-02 17:12 UTC, abvaidya commented on ui/src/components/utils/ReviewUtils.js
> +import { PERCENTAGE_OF_DAYS_TILL_NEXT_REVIEW } from '../constants/constants';
please add license text on all new files

2024-09-03 14:26 UTC, ArtjomsPorss commented on ui/src/__tests__/components/utils/ReviewUtils.test.js
> +import moment from 'moment-timezone';
done

2024-09-03 14:26 UTC, ArtjomsPorss commented on ui/src/components/utils/ReviewUtils.js
> +import { PERCENTAGE_OF_DAYS_TILL_NEXT_REVIEW } from '../constants/constants';
done

2024-09-04 01:00 UTC, abvaidya approved these changes

2024-09-04 01:00 UTC, merged