ui search capability to include services
AthenZ/athenz pull request #2832
Opened 2024-12-17 16:11 UTC by ArtjomsPorss

# Description

# Contribution Checklist:
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have read the [contribution guidelines](https://github.com/AthenZ/athenz/blob/master/CONTRIBUTING.md).**
- [ ] **Create an issue and link to the pull request.**

## Attach Screenshots (Optional)

2025-01-13 13:37 UTC, chandrasekhar1996 requested changes
1) We should indicate to the the user that the search results being shown is partial. (The search results is partial when [serviceMatchCount](https://github.com/AthenZ/athenz/blob/c2c94e09c7e5b297b651e6e818600080ef000a01/libs/java/server_common/src/main/java/com/yahoo/athenz/common/server/store/impl/JDBCConnection.java#L8318) field is set.) One way to do that can be to show it in Search results header below
<img width="1711" alt="Screenshot 2025-01-13 at 6 57 55 PM" src="https://github.com/user-attachments/assets/64a52f9d-2f57-4efc-beda-25d278f00eaa" />

2) The backend API has the capability to filter results based on domain name as well. Can you confirm if this story/PR was also meant to add support for that in UI? IIRC users can give "athenz:zms" as search term then UI can make search call with domain name set to athenz and service to zms

2025-01-13 13:37 UTC, chandrasekhar1996 commented on ui/src/server/handlers/api.js
> +                    debug(a.name, b.name);
remove in subsequent PR

2025-01-13 14:50 UTC, ArtjomsPorss commented on ui/src/server/handlers/api.js
> +                    debug(a.name, b.name);
regarding point 2 - services search accepts partial name of the service, without the domain name

2025-01-13 14:51 UTC, ArtjomsPorss commented on ui/src/server/handlers/api.js
> +                    debug(a.name, b.name);
will make change regarding point 1

2025-01-13 15:00 UTC, chandrasekhar1996 commented on ui/src/server/handlers/api.js
> +                    debug(a.name, b.name);
for point 2, the scenario I was thinking of is if searching for a service returns more than 100(default limit) results then user will never be able to use UI for search if the result is after top 100 even though the user may know the domain name which will help further narrow it down.

2025-01-16 16:39 UTC, ArtjomsPorss commented on ui/src/server/handlers/api.js
> +                    debug(a.name, b.name);
added 
![image](https://github.com/user-attachments/assets/45d6049e-10d9-47be-90ab-ce76f689ce5b)

2025-01-17 11:56 UTC, ArtjomsPorss commented on ui/src/pages/search/[type]/[searchterm].js
> +                                                color={colors.graphYellow}
questionmark in yellow colour

2025-01-17 11:57 UTC, ArtjomsPorss commented on ui/src/components/constants/constants.js
> +    'Maximum 100 results can be searched for at a time. Specify more characters in the search criteria to get better results.';
updated wording for question mark popup

2025-01-23 03:13 UTC, chandrasekhar1996 approved these changes

2025-01-23 22:35 UTC, merged